-- PG ADMIN QUERY

-- create columns
ALTER TABLE subjects 
ADD COLUMN id SERIAL PRIMARY KEY,
ADD COLUMN name VARCHAR(255) NOT NULL,
ADD COLUMN title VARCHAR(255) NOT NULL,
ADD COLUMN sub_title VARCHAR(255),
ADD COLUMN content VARCHAR(255)